[[headers]]
  # Apply to all paths
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    # You can add other CORS headers if needed, though for simple GET requests for static assets,
    # Access-Control-Allow-Origin is often the primary one.
    # Access-Control-Allow-Methods = "GET, OPTIONS"
    # Access-Control-Allow-Headers = "Content-Type"